"""
AI-Powered Report Generator
Generates professional security reports using MiniMax M2.5 AI
"""

from flask import Blueprint, request, jsonify
import asyncio
import logging
from typing import Dict, Optional
from datetime import datetime
from pathlib import Path
import json
import markdown
from weasyprint import HTML, CSS
import io

from ai_openrouter import get_pentester_ai_engine

logger = logging.getLogger(__name__)

report_bp = Blueprint('ai_reports', __name__, url_prefix='/api/reports')

class ReportGenerator:
    """Generate professional security reports"""
    
    REPORT_TEMPLATE = """
# Security Assessment Report

## Executive Summary
{executive_summary}

## Assessment Details
- **Target:** {target}
- **Date:** {date}
- **Assessor:** {assessor}
- **Assessment Type:** {assessment_type}

## Findings Summary
- **Critical:** {critical_count}
- **High:** {high_count}
- **Medium:** {medium_count}
- **Low:** {low_count}
- **Informational:** {info_count}

## Detailed Findings
{detailed_findings}

## Risk Assessment
{risk_assessment}

## Recommendations
{recommendations}

## Conclusion
{conclusion}

## Appendix

### Tools Used
{tools_used}

### Methodology
{methodology}

### References
{references}

---
*This report was generated by ShadowHack Elite Security Assessment Platform*
*Powered by Advanced AI Analysis (MiniMax M2.5)*
"""
    
    def __init__(self):
        self.engine = get_pentester_ai_engine()
    
    async def generate_report(
        self,
        findings: str,
        target: str,
        assessment_type: str = "Penetration Test",
        assessor: str = "ShadowHack Team",
        tools_used: list = None,
        include_pdf: bool = False
    ) -> Dict:
        """
        Generate comprehensive security report
        """
        
        try:
            # Generate report content using AI
            ai_report = await self.engine.generate_security_report(findings, target)
            
            # Parse findings into severity levels
            severity_counts = self._parse_severity_counts(findings)
            
            # Generate recommendations using AI
            recommendations = await self.engine.client.call_model(
                prompt=f"""Based on these findings: {findings}
                
Provide specific, actionable remediation recommendations organized by priority.""",
                system_prompt="You are a security expert providing remediation guidance.",
                temperature=0.5,
                max_tokens=1500
            )
            
            # Generate risk assessment using AI
            risk_assessment = await self.engine.client.call_model(
                prompt=f"""Based on these findings: {findings}
                
Provide a risk assessment including:
1. Overall risk level (Critical/High/Medium/Low)
2. Business impact analysis
3. Likelihood assessment
4. Risk matrix scoring""",
                system_prompt="You are a risk management expert.",
                temperature=0.4,
                max_tokens=1200
            )
            
            # Build complete report
            report_content = self.REPORT_TEMPLATE.format(
                executive_summary=ai_report[:500],
                target=target,
                date=datetime.now().strftime("%Y-%m-%d"),
                assessor=assessor,
                assessment_type=assessment_type,
                critical_count=severity_counts.get('critical', 0),
                high_count=severity_counts.get('high', 0),
                medium_count=severity_counts.get('medium', 0),
                low_count=severity_counts.get('low', 0),
                info_count=severity_counts.get('informational', 0),
                detailed_findings=ai_report,
                risk_assessment=risk_assessment,
                recommendations=recommendations,
                conclusion=await self._generate_conclusion(findings),
                tools_used=self._format_tools_list(tools_used or []),
                methodology=self._get_methodology(),
                references=self._get_references()
            )
            
            # Convert to HTML
            html_report = markdown.markdown(report_content)
            
            result = {
                'success': True,
                'report_content': report_content,
                'html_report': html_report,
                'summary': {
                    'target': target,
                    'assessment_type': assessment_type,
                    'date': datetime.now().isoformat(),
                    'severity_counts': severity_counts
                },
                'timestamp': datetime.now().isoformat()
            }
            
            # Generate PDF if requested
            if include_pdf:
                pdf_bytes = self._generate_pdf(html_report)
                result['pdf_base64'] = pdf_bytes
            
            return result
        
        except Exception as e:
            logger.error(f"Report generation error: {str(e)}")
            return {
                'success': False,
                'error': str(e)
            }
    
    def _parse_severity_counts(self, findings: str) -> Dict[str, int]:
        """Parse findings to count severity levels"""
        severity_map = {
            'critical': 0,
            'high': 0,
            'medium': 0,
            'low': 0,
            'informational': 0
        }
        
        for severity in severity_map.keys():
            severity_map[severity] = findings.lower().count(severity)
        
        return severity_map
    
    async def _generate_conclusion(self, findings: str) -> str:
        """Generate report conclusion using AI"""
        try:
            return await self.engine.client.call_model(
                prompt=f"""Based on these findings: {findings}
                
Write a professional conclusion that summarizes the overall security posture.""",
                system_prompt="You are a security assessment expert.",
                temperature=0.4,
                max_tokens=500
            )
        except:
            return "Assessment completed. Refer to detailed findings for comprehensive analysis."
    
    def _format_tools_list(self, tools: list) -> str:
        """Format tools list for report"""
        if not tools:
            return "- Nmap\n- Burp Suite\n- Metasploit Framework\n- Custom Security Scripts"
        return "\n".join([f"- {tool}" for tool in tools])
    
    def _get_methodology(self) -> str:
        """Get standard methodology description"""
        return """Assessment was conducted using industry-standard methodologies:

1. **Reconnaissance:** Information gathering about the target
2. **Scanning:** Network and vulnerability scanning
3. **Enumeration:** Detailed service enumeration
4. **Vulnerability Assessment:** Identification of weaknesses
5. **Exploitation:** Proof-of-concept where applicable
6. **Reporting:** Detailed documentation of findings"""
    
    def _get_references(self) -> str:
        """Get standard references"""
        return """- OWASP Top 10
- NIST Cybersecurity Framework
- CWE/CVSS Scoring
- PTES Technical Guidelines
- SANS Security Resources"""
    
    def _generate_pdf(self, html_content: str) -> bytes:
        """Generate PDF from HTML"""
        try:
            pdf_buffer = io.BytesIO()
            HTML(string=html_content).write_pdf(pdf_buffer)
            pdf_buffer.seek(0)
            return pdf_buffer.getvalue()
        except Exception as e:
            logger.error(f"PDF generation error: {str(e)}")
            return b""

# Global report generator
_report_gen = None

def get_report_generator():
    """Get global report generator instance"""
    global _report_gen
    if _report_gen is None:
        _report_gen = ReportGenerator()
    return _report_gen

# ============================================================================
# API Routes
# ============================================================================

@report_bp.route('/generate', methods=['POST'])
def generate_report():
    """
    Generate security report
    
    Request body:
    {
        "findings": "List of findings",
        "target": "Target name",
        "assessment_type": "Penetration Test",
        "assessor": "Your Name",
        "tools_used": ["nmap", "burp"],
        "include_pdf": false
    }
    """
    try:
        data = request.get_json()
        
        findings = data.get('findings', '')
        target = data.get('target', '')
        
        if not findings or not target:
            return jsonify({
                'success': False,
                'error': 'Missing required fields: findings, target'
            }), 400
        
        assessment_type = data.get('assessment_type', 'Penetration Test')
        assessor = data.get('assessor', 'ShadowHack Team')
        tools_used = data.get('tools_used', [])
        include_pdf = data.get('include_pdf', False)
        
        # Run async function
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            generator = get_report_generator()
            result = loop.run_until_complete(
                generator.generate_report(
                    findings=findings,
                    target=target,
                    assessment_type=assessment_type,
                    assessor=assessor,
                    tools_used=tools_used,
                    include_pdf=include_pdf
                )
            )
            return jsonify(result)
        finally:
            loop.close()
    
    except Exception as e:
        logger.error(f"Report generation error: {str(e)}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@report_bp.route('/template', methods=['GET'])
def get_template():
    """Get report template"""
    try:
        return jsonify({
            'success': True,
            'template': ReportGenerator.REPORT_TEMPLATE
        })
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

@report_bp.route('/export/<format>', methods=['POST'])
def export_report(format):
    """
    Export report in different formats
    
    Supported formats: markdown, html, pdf, json
    """
    try:
        data = request.get_json()
        report_content = data.get('report_content', '')
        filename = data.get('filename', f'report_{datetime.now().strftime("%Y%m%d_%H%M%S")}')
        
        if format == 'markdown':
            return {
                'content': report_content,
                'mime_type': 'text/markdown',
                'filename': f"{filename}.md"
            }
        
        elif format == 'html':
            html = markdown.markdown(report_content)
            return {
                'content': html,
                'mime_type': 'text/html',
                'filename': f"{filename}.html"
            }
        
        elif format == 'json':
            return {
                'content': json.dumps({'report': report_content}, indent=2),
                'mime_type': 'application/json',
                'filename': f"{filename}.json"
            }
        
        else:
            return jsonify({
                'success': False,
                'error': f'Unsupported format: {format}'
            }), 400
    
    except Exception as e:
        logger.error(f"Export error: {str(e)}")
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500
